CityOfZion/NeoLink

README.md, src/js/background.js, src/js/popup.js, src/popup.html
This sets up the harness to easily switch between main net and test net.
This also renames netwokStatus to activeNetwork which is clearer and should be more important if we did actual network state tests/feedback.
=> Easily select between main and test networks

package-lock.json, package.json, src/html/authorizeResult.html, src/js/popup.js
This PR adjust authorize results and removes buttons on that display.
=> Authorization Results

src/app/containers/Send/index.js
Errors and results were not being formatted properly or displayed at all. This PR resolves that.
=> send result formatting and errors

src/app/containers/CreateWallet/CreateWallet.css, src/app/containers/CreateWallet/index.js
This PR adds the ability to create a wallet. I need a little help with formatting but I'm going to roll this into a larger task as this is project-wide right now.
=> Create Wallet Functionality

.circleci/config.yml, package-lock.json, package.json
Run linting + tests + code coverage.
=> CircleCI + coveralls

package-lock.json, package.json
fixes https://github.com/CityOfZion/NeoLink/issues/71
=> Fix windows build

__tests__/containers/ExportWallet.test.js, src/app/containers/ExportWallet/ExportWallet.js, src/app/containers/ExportWallet/index.js, src/manifest.json
Ability to download wallet in NEP-6 format json file.
=> Export wallet functionality

README.md
=> Github Spelling Crrection

src/app/containers/App/App.css
Removed the scrollbars which were shown in the UI
Previous:
Now:
=> chore(app): removed scrollbars

src/app/components/FileUpload/FileUpload.css, src/app/components/FileUpload/index.js, src/app/components/ImportWalletInfo/ImportWalletInfo.css, src/app/components/ImportWalletInfo/index.js, src/app/components/Settings/index.js, src/app/components/successPages/ImportWalletSuccessPage/ImportWalletSuccessPage.css, src/app/components/successPages/ImportWalletSuccessPage/index.js, src/app/containers/ImportWallet/ImportWallet.css, src/app/containers/ImportWallet/ImportWallet.js
Completed redesign of NeoLink import wallet
=> Neolink import wallet redesign

README.md, __tests__/components/Login.test.js, __tests__/components/NetworkSwitcher.test.js, __tests__/containers/Home.test.js, package-lock.json, src/app/components/AccountInfo/AccountInfoDropDownContent/index.js, src/app/components/DropDown/index.js
Tests were throwing some warnings and errors some helper functions that were triggered by the testing code. I added the necessary code to make them work without complaining and changed a few proptypes where the isRequired prop was unnecessary.
=> Fix tests warnings

package-lock.json, src/app/components/AccountInfo/AccountInfoAmounts/index.js, src/app/components/SwitchAccountCard/SwitchAccountCard.css, src/app/components/SwitchAccountCard/index.js, src/app/containers/App/App.js, src/app/containers/ExportWallet/ExportWallet.css, src/app/containers/ExportWallet/ExportWallet.js, src/app/containers/SwitchAccount/SwitchAccount.css, src/app/containers/SwitchAccount/SwitchAccount.js, src/app/containers/SwitchAccount/index.js, src/data/mainNavigationData.js
Implemented redesign of export wallet page.
=> Neolink redesign export wallet

package.json, src/app/containers/App/App.css, src/app/containers/SendInvoke/SendInvoke.css, src/app/containers/SendInvoke/SendInvokeReadonly.js, src/app/containers/SendInvoke/index.js, src/app/containers/TestInvoke/index.js, src/app/containers/TestInvoke/testInvoke.css
Replaced and removed rmwc with custom components
Result one of the two screens affected:
=> chore(invoke): replaced rmvc with custom components

src/app/actions/account.js, src/app/containers/Asset/Asset.css, src/app/containers/Asset/Asset.js, src/app/containers/Asset/index.js, src/app/containers/Home/Home.css, src/app/containers/Home/Home.js, src/app/reducers/account.js, src/app/utils/api/neoscan.js
This update resolves a few bugs in asset management and also adds code to list any other assets in a users account as returned by getBalance
=> List balances for all assets on Home screen

package.json
fixed issue which caused webpack to fail compilcation
=> chore(deps): fixed issue, webpack not building

src/app/containers/ExportWallet/ExportWallet.css, src/app/containers/ExportWallet/ExportWallet.js, src/app/containers/ExportWallet/index.js, src/app/containers/ImportWallet/ImportWallet.css, src/app/containers/ImportWallet/ImportWallet.js
As discussed in discord this is the PR for adding in a back button
- Added a back button for consistency reasons
- Cleanup of exportWallet (removed type)
=> chore(settings): added back button for wallet import/exports

__tests__/components/__snapshots__/CustomNetworkList.test.js.snap
Updated snapshots to fix the circleci build
=> chore(build): fix build

package.json, src/app/containers/Send/Send.js, src/app/utils/api/neon.js, src/app/utils/api/neoscan.js
This code needed a rewrite and a some bugs were discovered. This has been updated. Testing is ongoing but this fix is to get the basic functionality restored. It still needs transaction confirmation display.
=> sendAsset Bugfix

src/app/components/PasswordModal/PasswordModal.js, src/app/components/successPages/SendSuccessPage/index.js, src/app/containers/Send/Send.js, src/app/utils/api/neon.js
- send card cancel button
- send card confirmation message and password modal
- promisified sendAsset and linked to SendSuccessPage
- Fixed SendSuccessPage transaction lookup network detection
=> Send Card Refinements

__tests__/components/__snapshots__/CustomNetworkList.test.js.snap, src/app/components/failPages/FailPage/FailPage.css, src/app/components/failPages/FailPage/index.js, src/app/containers/Send/Send.js, src/app/utils/api/neon.js
send card failure page (for transaction failures) and testing
=> failure page for send card

src/app/components/common/form/CustomNetworkForm/index.js, src/app/containers/AddCustomNetwork/AddCustomNetwork.js, src/app/containers/AddTransactionRemark/AddTransactionRemark.js, src/app/containers/EditCustomNetwork/EditCustomNetwork.js, src/app/containers/Send/Send.css, src/app/containers/Send/Send.js
- Fixed redux form state issue not persisting
- Fixed issue with faulty classname
- Removed redundant code and cleaned up prop validation
- Fixed react issue with `cssOnly` attribute
=> Chore(send): fixed redux form state issue
